// SPDX-License-Identifier: (see LICENSE)
// Mayam — Representation Model

import Foundation

// MARK: - Representation

/// Describes a single stored representation of a DICOM instance.
///
/// A DICOM SOP Instance may exist in multiple representations within the
/// archive — for example, the original uncompressed data and a JPEG 2000
/// compressed copy.  Each representation is recorded with its transfer syntax,
/// file path, and metadata.
///
/// The server uses these representations to implement **Unified Object
/// Presentation**: all copies of the same instance are presented to end users
/// as a single logical item, with the most appropriate representation served
/// automatically based on the client's accepted transfer syntaxes.
///
/// Reference: Milestone 4 — Unified Object Presentation
public struct Representation: Sendable, Equatable, Codable {

    /// Unique identifier for this representation.
    public let id: String

    /// The DICOM SOP Instance UID (0008,0018) this representation belongs to.
    public let sopInstanceUID: String

    /// The DICOM SOP Class UID (0008,0016).
    public let sopClassUID: String

    /// The DICOM Study Instance UID (0020,000D).
    public let studyInstanceUID: String

    /// The DICOM Series Instance UID (0020,000E).
    public let seriesInstanceUID: String

    /// Transfer syntax UID of this representation.
    public let transferSyntaxUID: String

    /// Relative file path within the archive root.
    public let filePath: String

    /// File size in bytes.
    public let fileSizeBytes: Int64

    /// Whether this is the original (as-received) representation.
    public let isOriginal: Bool

    /// Whether this representation was generated by a compressed-copy-on-receipt
    /// policy or a background batch transcoding job.
    public let isDerived: Bool

    /// Hex-encoded SHA-256 checksum of the file, or `nil` if checksums are
    /// disabled.
    public let checksumSHA256: String?

    /// The date and time when this representation was created.
    public let createdAt: Date

    /// The codec framework used to produce this representation, or `nil` for
    /// the original uncompressed copy.
    public let codec: CodecFramework?

    /// Creates a new representation descriptor.
    ///
    /// - Parameters:
    ///   - id: Unique identifier.
    ///   - sopInstanceUID: DICOM SOP Instance UID (0008,0018).
    ///   - sopClassUID: DICOM SOP Class UID (0008,0016).
    ///   - studyInstanceUID: DICOM Study Instance UID (0020,000D).
    ///   - seriesInstanceUID: DICOM Series Instance UID (0020,000E).
    ///   - transferSyntaxUID: Transfer syntax UID.
    ///   - filePath: Relative path in the archive.
    ///   - fileSizeBytes: File size in bytes.
    ///   - isOriginal: Whether this is the original representation.
    ///   - isDerived: Whether this was generated by a policy.
    ///   - checksumSHA256: Hex SHA-256 checksum, or `nil`.
    ///   - createdAt: Creation timestamp.
    ///   - codec: The codec framework used, or `nil`.
    public init(
        id: String = UUID().uuidString,
        sopInstanceUID: String,
        sopClassUID: String,
        studyInstanceUID: String = "UNKNOWN",
        seriesInstanceUID: String = "UNKNOWN",
        transferSyntaxUID: String,
        filePath: String,
        fileSizeBytes: Int64,
        isOriginal: Bool = true,
        isDerived: Bool = false,
        checksumSHA256: String? = nil,
        createdAt: Date = Date(),
        codec: CodecFramework? = nil
    ) {
        self.id = id
        self.sopInstanceUID = sopInstanceUID
        self.sopClassUID = sopClassUID
        self.studyInstanceUID = studyInstanceUID
        self.seriesInstanceUID = seriesInstanceUID
        self.transferSyntaxUID = transferSyntaxUID
        self.filePath = filePath
        self.fileSizeBytes = fileSizeBytes
        self.isOriginal = isOriginal
        self.isDerived = isDerived
        self.checksumSHA256 = checksumSHA256
        self.createdAt = createdAt
        self.codec = codec
    }
}

// MARK: - RepresentationSet

/// A collection of all representations for a single SOP Instance.
///
/// Implements **Unified Object Presentation** by grouping all derivatives
/// of the same DICOM instance and providing methods to select the best
/// representation for a given client.
public struct RepresentationSet: Sendable, Equatable {

    /// The SOP Instance UID shared by all representations.
    public let sopInstanceUID: String

    /// All available representations, ordered by creation date.
    public private(set) var representations: [Representation]

    /// Creates a new representation set.
    ///
    /// - Parameters:
    ///   - sopInstanceUID: The shared SOP Instance UID.
    ///   - representations: Initial representations.
    public init(sopInstanceUID: String, representations: [Representation] = []) {
        self.sopInstanceUID = sopInstanceUID
        self.representations = representations
    }

    /// The original (as-received) representation, if present.
    public var original: Representation? {
        representations.first(where: \.isOriginal)
    }

    /// All derived (compressed-copy) representations.
    public var derived: [Representation] {
        representations.filter(\.isDerived)
    }

    /// The set of available transfer syntax UIDs.
    public var availableTransferSyntaxUIDs: Set<String> {
        Set(representations.map(\.transferSyntaxUID))
    }

    /// The total number of representations.
    public var count: Int {
        representations.count
    }

    /// Adds a new representation to the set.
    ///
    /// - Parameter representation: The representation to add.
    public mutating func add(_ representation: Representation) {
        representations.append(representation)
    }

    /// Returns the best representation for the given client-accepted
    /// transfer syntaxes.
    ///
    /// Selection order:
    /// 1. Direct match (client supports a stored transfer syntax).
    /// 2. Prefer lossless over lossy among matches.
    /// 3. Fall back to the original representation.
    ///
    /// - Parameter clientAcceptedUIDs: Transfer syntax UIDs the client accepts.
    /// - Returns: The best matching representation, or `nil` if no match.
    public func bestMatch(for clientAcceptedUIDs: Set<String>) -> Representation? {
        // Direct match: prefer lossless
        let directMatches = representations.filter { clientAcceptedUIDs.contains($0.transferSyntaxUID) }
        if let lossless = directMatches.first(where: { TransferSyntaxRegistry.isLossless($0.transferSyntaxUID) }) {
            return lossless
        }
        if let first = directMatches.first {
            return first
        }

        // Fall back to original
        return original
    }
}
